[project]
name = "{{ .ProjectName }}"
version = "0.1.0"
description = "{{ .ProjectDescription }}"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beamlit>=0.0.44",
]
[dependency-groups]
dev = [
    "ruff>=0.8.2",
]

[tool.ruff]
indent-width = 4

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["E", "F"]
