name: Deploy Blaxel Agent

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: blaxel/blaxel-action@v1
        with:
          workspace: {{ .Workspace }}
          apikey: {{ `${{ secrets.BL_API_KEY }}` }}
      - run: |
          bl deploy
