name: Deploy Beamlit Agent

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: beamlit/beamlit-action@v1
        with:
          workspace: {{ .Workspace }}
          apikey: {{ `${{ secrets.BEAMLIT_API_KEY }}` }}